# Numpy Array

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6]]

In [6]:
my_mat

[[1, 2, 3], [4, 5, 6]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6]])

Quick Generate Array

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [11]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [13]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [14]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [17]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [18]:
np.random.rand(5)

array([ 0.60247376,  0.31475103,  0.80744124,  0.27048972,  0.03397202])

In [19]:
np.random.rand(5,5)

array([[  3.40415513e-01,   8.96022706e-01,   8.84995697e-01,
          9.83662243e-01,   4.80211087e-01],
       [  5.69374627e-01,   2.71511139e-01,   9.87790625e-01,
          1.84178386e-05,   7.76858280e-01],
       [  1.31531120e-01,   4.20899693e-01,   5.95918257e-01,
          4.83500340e-01,   3.44157425e-01],
       [  8.20520895e-01,   7.93842758e-01,   2.83374648e-01,
          3.11305139e-01,   1.14661846e-02],
       [  9.00407593e-01,   9.88875756e-01,   8.46029529e-01,
          3.31684801e-01,   3.04942117e-01]])

In [20]:
np.random.randn(2)

array([ 0.11799186,  0.42288434])

In [21]:
np.random.randint(1,100)

31

In [22]:
np.random.randint(1,100,10)

array([91, 77, 12, 88, 44,  6, 35, 54, 59, 13])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0,50,10)

In [26]:
ranarr

array([36, 13,  1, 27, 10, 45, 35, 38, 18, 32])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr.shape

(25,)

In [29]:
arr.dtype

dtype('int64')

In [30]:
from numpy.random import randint

In [31]:
randint(2,10)

3

# Numpy Array Index & Selection

In [33]:
arr = np.arange(0,11)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[8]

8

In [37]:
arr[1:5]

array([1, 2, 3, 4])

In [38]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [40]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
arr[0:5] =100

In [43]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
arr = np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
slice_of_arr = arr[0:6]

In [47]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [48]:
slice_of_arr[0:3] =22

In [49]:
arr

array([22, 22, 22,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr_copy = arr.copy()

In [51]:
arr_copy

array([22, 22, 22,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [53]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
arr_2d[0][0]

5

In [57]:
arr_2d[2,2]

45

In [59]:
arr = np.arange(1,11)

In [60]:
bool_arr = arr >5

In [61]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [62]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [63]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

# Numpy Operation
    Array with Array
    Array with Scalars
    Universal Array Functions

In [64]:
arr = np.arange(1,11)

In [65]:
arr/arr

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [66]:
arr*100

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [67]:
arr/100

array([ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ])

In [68]:
np.sqrt(arr)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766])

In [69]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [70]:
np.max(arr)

10

In [71]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])